### Created by Dr. Benjamin Richards (b.richards@qmul.ac.uk) 

### Download base image from cern repo on docker hub
FROM tooldaq/core:latest

### Run the following commands as super user (root):
USER root

RUN yum install -y httpd \
    postgresql-server
    sudo \
    && yum clean all \
    && rm -rf /var/cache/yum

ADD setup.tar.gz /

    

### Open terminal
CMD ["/bin/bash"]
 