#!/bin/bash

set -e

database=daq
host=localhost
port=5432

argv=(`getopt -l database:,host:,port: -o d:h:p: -- "$@"`)
eval "set -- ${argv[@]}"
while [[ $1 != -- ]]; do
  case $1 in
    --database|-d) database=$2; shift 2;;
    --host|-h)     host=$2;     shift 2;;
    --port|-p)     port=$2;     shift 2;;
  esac
done
shift

if (($#)) && [[ $1 != - ]]; then
  exec < "$1"
fi

fields=`sed -nr '1{s,1?,,g; p; q}'`
sed 's/$/,,0/' |
  psql -d "$database" \
       -h "$host" \
       -p "$port" \
       -c "\\copy pmt ($fields, type, size) from stdin with delimiter ','"
