name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ESLint globally
      run: |
        sudo apt-get update
        sudo apt-get install -y eslint  # Install ESLint globally

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Install Clang-Tidy
      run: |
        sudo apt-get install -y clang-tidy

    # - name: Install Perl and cpanm
    #   run: |
    #     sudo apt-get install -y perl
    #     sudo apt-get install -y cpanminus  # Install cpanm tool

    # - name: Install missing Perl dependencies
    #   run: |
    #     sudo cpanm Module::Pluggable  # Install the missing dependency
    #     sudo cpanm --installdeps Perl::Critic  # Install all dependencies for Perl::Critic

    # - name: Install Perl::Critic
    #   run: |
    #     sudo cpanm Perl::Critic  # Install Perl::Critic module

    - name: Lint JavaScript
      run: npx eslint .

    - name: Lint HTML
      run: npx htmlhint .

    - name: Lint CSS
      run: npx stylelint "**/*.css"

    - name: Lint Shell scripts
      run: shellcheck **/*.sh

    - name: Lint C++ code
      run: clang-tidy **/*.cpp

    # - name: Lint Perl
    #   run: perlcritic **/*.pl
